name: Hacktoberfest

on:
  # run for all pushes to master branch
  push:
    branches:
      - master

jobs:
  # add hacktoberfest-accepted label to PRs closed by a commit on master
  merged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Check wether repo participates in Hacktoberfest
        run: |
          gh config set prompt disabled && echo "::set-output name=label::$(
            gh repo view --json repositoryTopics --jq '.repositoryTopics[].name' | grep '^hacktoberfest$')"
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Search relevant commit message lines starting with Closes/Merges
        run: |
          git log --format=email ${{ github.event.before }}..${{ github.event.after }} | \
            egrep "^(Closes|Merges) " | sort | uniq | tee log
        if: steps.check.outputs.label == 'hacktoberfest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Search for Number-based PR references
        run: |
          egrep -o "#([0-9]+)" log | cut -d# -f2 | sort | uniq | xargs -t -n1 -I{} \
            gh pr view {} --json number,labels \
              --jq '{number, label: .labels[].name} | [.number, .label] | join(":")' | tee /dev/stderr | \
            egrep -o '^([0-9]+):hacktoberfest$' | cut -d: -f1 | sort | uniq | xargs -t -n1 -I {} \
              gh pr edit {} --remove-label 'hacktoberfest' --add-label 'hacktoberfest-accepted'
        if: steps.check.outputs.label == 'hacktoberfest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Search for URL-based PR references
        run: |
          egrep -o "github.com/(.+)/(.+)/pull/([0-9]+)" log | sort | uniq | xargs -t -n1 -I{} \
            gh pr view "https://{}" --json number,labels \
              --jq '{number, label: .labels[].name} | [.number, .label] | join(":")' | tee /dev/stderr | \
            egrep -o '^([0-9]+):hacktoberfest$' | cut -d: -f1 | sort | uniq | xargs -t -n1 -I {} \
              gh pr edit {} --remove-label 'hacktoberfest' --add-label 'hacktoberfest-accepted'
        if: steps.check.outputs.label == 'hacktoberfest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
