name: Hacktoberfest

on:
  pull_request:
    types:
      - opened

# TODO: replace hacktobertest with hacktoberfest (test with fest) before merge!
jobs:
  # add hacktoberfest label starting from September 30th till November 1st
  opened:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Add label to PRs opened within timeframe
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label 'hacktobertest'
        if: |
          ${{ contains(github.event.pull_request.created_at, '-09-30T')
           || contains(github.event.pull_request.created_at, '-10-')
           || contains(github.event.pull_request.created_at, '-11-01T') }}
